# 커밋 먹는 뱀 그래프 생성을 위한 GitHub Action
name: Generate Snake

# 커밋이 진행 될 시간 (6시간 마다 진행)

on:
  schedule:
    - cron: "0 */6 * * *"

# 이 명령을 사용하면 작업 탭에서 작업을 자동으로 실행할 수 있음
  workflow_dispatch:

# 이 워크플로의 실행 순서
jobs:
  build:
# 작업이 실행될 러너의 유형
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

    # 뱀 생성
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SSEUNGkr
         
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # 빌드 상태를 표시합니다. 디버깅을 더 쉽게 만듭니다(문제가 있는 경우).
      - run: git status

      # 변경 사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
         
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}